flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = TextAreaField(label="Content", validators=[DataRequired()])
    submit = SubmitField(label="Create Post")

flaskblog/main/routes.py
from flask import Blueprint, render_template, request

from flaskblog.models import Post

main = Blueprint("main", __name__)


@main.route(rule="/")
@main.route(rule="/home")
def home():
    page = request.args.get("page", default=1, type=int)
    posts = Post.query.order_by(Post.posted_date.desc()).paginate(per_page=5, page=page)
    return render_template(template_name_or_list="home.html", posts=posts)


@main.route(rule="/about")
def about():
    return render_template(template_name_or_list="about.html", title="About")

flaskblog/posts/routes.py
from flask import Blueprint, flash, render_template, redirect, request, url_for, abort
from flask_login import current_user, login_required

from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint("posts", __name__)


@posts.route(rule="/new-post", methods=["GET", "POST"])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data, content=form.content.data, author=current_user
        )
        db.session.add(post)
        db.session.commit()
        flash(message="Your post has been created!", category="success")
        return redirect(url_for("main.home"))
    return render_template(
        "new_post.html", title="New Post", form=form, legend="New Post"
    )


@posts.route(rule="/post/<int:post_id>")
def post(post_id: int):
    post = Post.query.get_or_404(post_id)
    return render_template("post.html", title=post.title, post=post)


@posts.route(rule="/post/<int:post_id>/update", methods=["GET", "POST"])
@login_required
def update_post(post_id: int):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        # No need to add to the session as the post is already in the db.
        db.session.commit()
        flash(message="Your post has been updated!", category="success")
        return redirect(url_for("posts.post", post_id=post.id))
    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content
    return render_template(
        "new_post.html", title="Update Post", form=form, legend="Update Post"
    )


@posts.route(rule="/post/<int:post_id>/delete", methods=["POST"])
@login_required
def delete_post(post_id: int):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(message="Your post has been deleted!", category="success")
    return redirect(url_for("main.home"))

flaskblog/users/routes.py
from flask import Blueprint, redirect, url_for, flash, request, render_template
from flask_login import current_user, login_user, logout_user, login_required

from flaskblog import db, bcrypt
from flaskblog.models import AppUser, Post
from flaskblog.users.forms import (
    RegistrationForm,
    LoginForm,
    RequestResetForm,
    ResetPasswordForm,
    UpdateAccountForm,
)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint("users", __name__)


# methods parameter denotes the HTTP methods this route will accept.
@users.route(rule="/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    """This instantiates the form class imported from forms.py that
    is then passed to register.html using Jinja templating."""
    form = RegistrationForm()
    # Validate the input of the form
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = AppUser(
            username=form.username.data, email=form.email.data, password=hashed_password
        )
        db.session.add(user)
        db.session.commit()
        """Flash (Flask class) allows you to show a message (message parameter).
        Category parameter is the bootstrap css class 'success' for styling."""
        flash(
            message="Your account has been created! You are now able to log in.",
            category="success",
        )
        # url_for dynamically retrieves the URL of the home route.
        return redirect(url_for("users.login"))
    return render_template("register.html", title="Register", form=form)


@users.route(rule="/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = LoginForm()
    # If input passes the validation defined in forms.py...
    if form.validate_on_submit():
        # Query the database for the user, using their email.
        user = AppUser.query.filter_by(email=form.email.data).first()
        # Check user exists and password matches hashed password.
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # Log the user in with flask_login.
            login_user(user, remember=form.remember.data)
            # Get the (optional) 'next' argument passed by the prev page.
            next_page = request.args.get("next")
            # If the 'next' argument was provided, redirect to that page, else home.
            return redirect(next_page) if next_page else redirect(url_for("main.home"))
        else:
            flash(
                message="Invalid login credentials!",
                category="danger",
            )
    return render_template("login.html", title="Login", form=form)


@users.route(rule="/logout")
def logout():
    logout_user()
    return redirect(url_for("main.home"))


@users.route(rule="/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash(message="Your account has been updated!", category="success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template(
        "account.html", title="Account", image_file=image_file, form=form
    )


@users.route(rule="/user/<string:username>")
def user_posts(username):
    user = AppUser.query.filter_by(username=username).first_or_404()
    page = request.args.get("page", default=1, type=int)
    posts = (
        Post.query.filter_by(author=user)
        .order_by(Post.posted_date.desc())
        .paginate(per_page=5, page=page)
    )
    return render_template(
        template_name_or_list="user_posts.html", posts=posts, user=user
    )


@users.route(rule="/reset_password", methods=["GET", "POST"])
def reset_request():
    # If the user is already logged in, redirect them to the homepage.
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = AppUser.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash(
            message="An email has been sent with instructions on resetting your password.",
            category="info",
        )
        return redirect(url_for("users.login"))
    return render_template(
        template_name_or_list="reset_request.html", title="Reset Password", form=form
    )


@users.route(rule="/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    # If the user is already logged in, redirect them to the homepage.
    if current_user.is_authenticated:
        return redirect(url_for("main.home"))
    user = AppUser.verify_reset_token(token)
    if user is None:
        flash(message="That is an invalid or expired token!", category="warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    # Validate the input of the form
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        """Flash (Flask class) allows you to show a message (message parameter).
        Category parameter is the bootstrap css class 'success' for styling."""
        flash(
            message="Your password has been updated! You are now able to log in.",
            category="success",
        )
        # url_for dynamically retrieves the URL of the home route.
        return redirect(url_for("users.login"))
    return render_template(
        template_name_or_list="reset_token.html", title="Reset Password", form=form
    )

flaskblog/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About page!</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="row">
            <div class="col-md-3">
                <img class="rounded-circle account-img" src="{{ image_file }}" alt="profile picture">
            </div>
            <div class="col-md-9">
                <div class="media">
                    <div class="media-body">
                        <h2 class="account-heading">{{ current_user.username }}</h2>
                        <p class="text-secondary">{{ current_user.email }}</p>
                    </div>
                </div>
            </div>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Info</legend>
                    {# There is a lot of validation boilerplate here. You
                               can use the flask-bootstrap extension to simplify
                               this but doing it this way offers more control. #}
                    <div class="form-group">
                        {# Label refers to the label field of the object in forms.py. #}
                        {{ form.username.label(class="form-control-label") }}
                        {# If there are errors when submitting the form... #}
                        {% if form.username.errors %}
                            {# Add the bootstrap is-invalid class to the form... #}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            {# And using the bootstrap class for error feedback... #}
                            <div class="invalid-feedback">
                                {# Print all the errors in a span tag. #}
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {# If the form is valid, proceed normally. #}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {# Add the bootstrap is-invalid class to the form... #}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            {# And using the bootstrap class for error feedback... #}
                            <div class="invalid-feedback">
                                {# Print all the errors in a span tag. #}
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {# If the form is valid, proceed normally. #}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.picture.label() }}<br/>
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span><br/>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>

        </div>
    </div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <img class="rounded-circle article-img"
                         src="{{ url_for("static", filename="profile_pics/" + post.author.image_file) }}"
                         alt="Profile Picture">
                    <a class="mr-2"
                       href="{{ url_for("users.user_posts", username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted"> on {{ post.posted_date.strftime('%-d %B %Y') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for("posts.post", post_id=post.id) }}">{{ post.title }}</a>
                </h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for("main.home", page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for("main.home", page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <!-- My custom CSS (url_for in the jinja template dynamically
         populates the path to the file) -->
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet" type="text/css">
</head>
<body>
<!-- Bootstrap navbar -->
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">Max's Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav ms-auto">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<!-- Bootstrap Main Block -->
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.</p>
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
            </div>
        </div>
    </div>
</main>
<!--Bootstrap scripts -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js"
        integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa"
        crossorigin="anonymous"></script>
</body>
</html>

flaskblog/templates/login.html
{% extends "layout.html" %} {% block content %}
    <div class="content-section">
        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {# There is a lot of validation boilerplate here. You can use the
                flask-bootstrap extension to simplify this but doing it this way offers
                    more control. #}
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {# Add the bootstrap is-invalid class to the form... #}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        {# And using the bootstrap class for error feedback...#}
                        <div class="invalid-feedback">
                            {# Print all the errors in a span tag. #}
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {# If the form is valid, proceed normally. #}
                        {{ form.email(class="form-control form-control-lg") }} {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {# Add the bootstrap is-invalid class to the form... #}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        {# And using the bootstrap class for error feedback...#}
                        <div class="invalid-feedback">
                            {# Print all the errors in a span tag. #}
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %} {# If the form is valid, proceed normally. #}
                        {{ form.password(class="form-control form-control-lg") }} {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }} {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for("users.reset_request") }}">Forgot Password?</a>
            </small>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account?<a class="ml-2" href="{{ url_for('users.register') }}">Register!</a>
        </small>
    </div>
{% endblock content %}

flaskblog/templates/new_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                {# There is a lot of validation boilerplate here. You can use the
                flask-bootstrap extension to simplify this but doing it this way offers
                    more control. #}
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                        {# Add the bootstrap is-invalid class to the form... #}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        {# And using the bootstrap class for error feedback...#}
                        <div class="invalid-feedback">
                            {# Print all the errors in a span tag. #}
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {# If the form is valid, proceed normally. #}
                        {{ form.title   (class="form-control form-control-lg") }} {% endif %}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                        {# Add the bootstrap is-invalid class to the form... #}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        {# And using the bootstrap class for error feedback...#}
                        <div class="invalid-feedback">
                            {# Print all the errors in a span tag. #}
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %} {# If the form is valid, proceed normally. #}
                        {{ form.content(class="form-control form-control-lg") }} {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <img class="rounded-circle article-img"
                     src="{{ url_for("static", filename="profile_pics/" + post.author.image_file) }}"
                     alt="Profile Picture">
                <a class="mr-2"
                   href="{{ url_for("users.user_posts", username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted"> on {{ post.posted_date.strftime('%-d %B %Y') }}</small>
                {% if post.author == current_user %}
                    <a class="btn btn-secondary btn-sm mt-1 mb-1"
                       href="{{ url_for("posts.update_post", post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-primary btn-danger btn-sm mt-1 mb-1" data-bs-toggle="modal"
                            data-bs-target="#deleteModal">
                        Delete
                    </button>
                {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete post?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to delete this post?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for("posts.delete_post", post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                {# There is a lot of validation boilerplate here. You can use the
                flask-bootstrap extension to simplify this but doing it this way offers
                    more control. #}
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {# Add the bootstrap is-invalid class to the form... #}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        {# And using the bootstrap class for error feedback...#}
                        <div class="invalid-feedback">
                            {# Print all the errors in a span tag. #}
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {# If the form is valid, proceed normally. #}
                        {{ form.email(class="form-control form-control-lg") }} {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="#">Forgot Password?</a>
            </small>
        </form>
    </div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}
{% block content %}
    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <img class="rounded-circle article-img"
                         src="{{ url_for("static", filename="profile_pics/" + post.author.image_file) }}"
                         alt="Profile Picture">
                    <a class="mr-2"
                       href="{{ url_for("users.user_posts", username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted"> on {{ post.posted_date.strftime('%-d %B %Y') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for("posts.post", post_id=post.id) }}">{{ post.title }}</a>
                </h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4"
                   href="{{ url_for("users.user_posts", page=page_num, username=user.username) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4"
                   href="{{ url_for("users.user_posts", page=page_num, username=user.username) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}